import type { Metadata } from "next";
import "./globals.css";

import MyHeader from "@/components/my-header"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fr"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <MyHeader/>
        
        <main className="w-full max-w-7xl py-8 px-4 mx-auto bg-white dark:bg-black border border-amber-600">
          {children}
        </main>
        </body>
    </html>
  );
}
